Supports Scroll gcode messages in terminal
bigtreetech/BIGTREETECH-TouchScreenFirmware pull request #1171
Opened 2020-10-13 05:36 UTC by Subcircuit

### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

### Benefits

### Related Issues

2020-10-13 19:26 UTC, radek8 commented
How does the terminal window close?

2020-10-14 11:18 UTC, Subcircuit commented
> How does the terminal window close?

Page turning is under the back button, and the back button is still there.

2020-10-14 20:49 UTC, radek8 commented
OK, I missed the button. Thank you

2020-10-21 00:17 UTC, StarNamer commented
@Subcircuit I just submitted a [PR ](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1191)to add an extra column to the terminal keys. Originally (#1181 ), I was just going to add the F key (as I find typing the F parameter common as in 'G0 F60 Z0') but decided to add an extra column give a better layout (X Y Z E on one row) and allow a few extra keys (I, J, P, R). The only only place this conflicts with what you've done is that you've defined the bottom right position as ">". But as far as I can see, you don't use it for anything and I'm not aware of GCode using it. Is there a reason for this key being added? I didn't include it in my change, but since I added several punctuation keys on the ABC page, this could easily replace one of them since the only essential punctuation characters are "!" and "#" (for M32), "/" for file paths and "~" for 8.3 truncated filenames.

2020-10-22 20:32 UTC, oldman4U commented
Hello @Subcircuit.

Hope you are still monitoring this PR. Could you please add this to this PR, so that the FR related to the function you developed is automatically closed.

Thank you

resolves #1112

2020-10-25 18:54 UTC, digant73 requested changes
hi,
As an enhancement I will add a page/total pages indication in the same bar where you provided the "back" button. It helps the navigation through all the pages

2020-10-28 04:04 UTC, BlackDragon2020 commented
I will add that this was something that made me sad as using this function was one of the reasons to get it, but with no scrolling it was maybe 75% usable at best.

this was one of the bugs/ issues / FR i was going to look in to or recode. I will give this a look soon. thanks

2020-10-28 09:27 UTC, digant73 commented
IMHO once the bar providing the "back" button is present, I would place into it also the UP and DOWN buttons. It makes more intuitive the navigation (instead of pressing on the upper or lower part of the screen. I wouls also place the bar in the bottom part of the screen instead of the upper part (that simply to avoid to cover with the finger the screen). I would provide something like:

+------------------------+
|                        |
|                        |
|                        |
|                        |
|                        |
|                        |
+------------------------+
| _1/4______^__v__BACK_|

2020-10-29 10:52 UTC, bigtreetech commented
@digant73 hello,  I've rearranged this menu.

2020-10-29 13:20 UTC, digant73 commented
> @digant73 hello, I've rearranged this menu.

Ok, I will have a look.
Something more I would like to change is also the background and foreground colors. Although I don't have problem with my eyes, the grey background and the black foreground are not the best choice (too less contrast). Normally the preferred colors are black for the background and yellow (or orange) for the foreground. However, I could work on these minor improvements in the future (after this PR is merged).
My idea is also to review the main page. The "send" and "back" buttons should be located in the bottom part. They are more compliant with the standard menus (where the back button is in the bottom part of the screen). Also it makes (IMHO) more comfortable the use of the buttons. Also that blue and yellow colors seems not consistent with the rest of the layout. Just my opinion

2020-11-02 01:29 UTC, merged