Feature probe level corner
bigtreetech/BIGTREETECH-TouchScreenFirmware pull request #1742
Opened 2021-03-18 10:42 UTC by Cal1sto

### Requirements

New Feature request to have the Marlin function of Level Corner on the TFT with more function and for best leveling experience with a probe.

### Description

The Level corner function added in ABL menu give the potentiality to quick level the bed by measuring with the probe the 4 corner and adjust it, the tested point could be adjusted like the manual leveling

### Benefits

Easy and very quick bed leveling could be performed with this function and usefull for bed level check.

2021-03-18 13:16 UTC, oldman4U commented
Nice👍🏻

2021-03-18 19:18 UTC, digant73 requested changes

2021-03-18 20:07 UTC, Cal1sto commented on TFT/src/User/API/parseACK.c
> +        mblUpdateStatus(true);
no this is wrong  please let ablUpdateStatus(true);

2021-03-18 20:14 UTC, Cal1sto commented on TFT/src/User/API/coordinate.c
> +// Set level corner position the measured Z offset from probe, see in ABL.c menu refreshLevelCornerValue(MENUITEMS levelItems) and value get from parseACK.c
Done

2021-03-18 20:14 UTC, Cal1sto commented on TFT/src/User/API/coordinate.c
> +// Get level corner position the measured Z offset from probe, see in ABL.c menu refreshLevelCornerValue(MENUITEMS levelItems) and value get from parseACK.c
Done

2021-03-18 20:15 UTC, Cal1sto commented on TFT/src/User/API/coordinate.h
> -
Done

2021-03-18 20:18 UTC, Cal1sto commented on TFT/src/User/API/menu.h
> + uint8_t   enabled[LIVEICON_LINES+1];
Done, thanks

2021-03-18 20:20 UTC, Cal1sto commented on TFT/src/User/API/menu.h
> - uint8_t   enabled[LIVEICON_LINES];
Done

2021-03-18 20:21 UTC, Cal1sto commented on TFT/src/User/API/parseACK.c
> +      // G30 feedback to get the 4 corners Z value returned by Marlin for LevelCorner function in ABL.c
Done

2021-03-18 20:22 UTC, Cal1sto commented on TFT/src/User/API/parseACK.c
> +        mblUpdateStatus(true);
wrong correction done during compilation, i roll it back already to  ablUpdateStatus

2021-03-18 20:27 UTC, Cal1sto commented on TFT/src/User/Configuration.h
>  //===========================================================================
ok, rolled back to original one from bigreetech.master

2021-03-18 20:31 UTC, Cal1sto commented on TFT/src/User/Menu/BedLevelingLayer2.c
> +      bedLevelingLayer2Items.items[3].icon = ICON_LEVELCORNER;
Thanks logical ;-) - done

2021-03-18 20:35 UTC, Cal1sto commented on platformio.ini
>  ; Please visit documentation for the other options and examples
Original Platformio.ini restored

2021-03-18 20:51 UTC, Cal1sto reviewed
#define STRING_LEVELCORNER            "Level corner" is too long replaced with "L corner"

2021-03-18 21:11 UTC, Cal1sto reviewed
Remove ABL.c and ABL.h from this request no change performed there from original, this was done on previous master state

2021-03-18 21:16 UTC, Cal1sto commented
LevelCorner.c and LevelCorner.h replace the old implementation in ABL.c and ABL.h done on the old Master state before change with BedLevelingLayer2.c and BedLevelingLayer2.h  -- > remove from this request both ABL.c and ABL.h

2021-03-18 22:37 UTC, oldman4U commented
Hi Cal1sto.

Would it be possible to reduce the number of different icons used for this functionality, or to use Icons which are already available? There are point_1 to point_5 bmp's available today which do the same but only without the sensor.

This would be great, thank you

2021-03-18 23:39 UTC, Cal1sto commented
Hi oldman4U,

I understood why (limited free space), i will check if i could move the measured value bellow the icone, and find a way to clear the label area to display the value change.

2021-03-19 00:07 UTC, Cal1sto commented
Hi oldman4U,

Only one new icone left the levelcorner.bmp all other replaced with the leveling one "POINT_1" .... 
LevelCorner.c, menu.c and icon_list.inc updated / adapted for the new text location

2021-03-19 01:22 UTC, Guilouz commented
I redesigned icons to stay in the same spirit as the others.

![Sans titre-1](https://user-images.githubusercontent.com/12702322/111718208-cd22aa00-8859-11eb-900d-52a029d2be5e.jpg)

[Level Corner BMP.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6168020/Level.Corner.BMP.zip)

2021-03-19 07:10 UTC, Cal1sto commented
New icone proposal fron Guilouz added

2021-03-19 10:25 UTC, bigtreetech commented
Hello, I'm going to release a new stable version of firmware on this weekend(3/21), so major changes won't be merged into the main branch for the time being. When the new version is released, I will merge this PR immediately.

2021-03-19 12:47 UTC, Cal1sto commented
Thanks bigtreetech i will inform the community about this good news , take care and have great time

2021-03-19 13:24 UTC, Cal1sto commented
The bmp delivered by Guilouz, was defect and could not be read during the import(update) on the device, i open it and just save it in same location, after that the bmp format was ok.

2021-03-19 13:36 UTC, Guilouz commented
> The bmp delivered by Guilouz, was defect and could not be read during the import(update) on the device, i open it and just save it in same location, after that the bmp format was ok.

Very strange, they are exported in bmp 24 bits from photoshop

2021-03-19 13:50 UTC, Cal1sto commented
Yes i saw that it's very strange (Je sait j'ai vue cela) , I use GIMP for this type of purpose and he was able to read it, but strange he generate 66 bytes more .

2021-03-19 14:11 UTC, Guilouz commented
> Yes i saw that it's very strange (Je sait j'ai vue cela) , I use GIMP for this type of purpose and he was able to read it, but strange he generate 66 bytes more .

I will try your PR tonight, i will see the issue with bmp files, they must have all the same size.

2021-03-19 14:45 UTC, Cal1sto commented
I found why i provide 66 bytes more and why you provide 2 byte more at the end of the file i commit now the last fully correct files that is readable, and standard.
![image](https://user-images.githubusercontent.com/47449942/111798229-2aeeda80-88ca-11eb-8981-709db318d3ae.png)

2021-03-19 21:25 UTC, oldman4U commented
@Acenotass @AntoszHUN @bepstein111

One Icon more, sorry.

But like BTT wrote, there is no need to hurry, as all new features will be released next week, once the new firmware is available.

Thank you all!

2021-03-19 21:59 UTC, digant73 requested changes

2021-03-19 21:59 UTC, digant73 commented on TFT/src/User/API/parseACK.c
> +      }
remove the trailing spaces after "}"

2021-03-19 21:59 UTC, digant73 commented on TFT/src/User/API/parseACK.c
> +          if (ack_seen("Z: ")) {
put all the "{" in a new line

2021-03-19 21:59 UTC, digant73 commented on TFT/src/User/Configuration.h
>  /**
restore the original file

2021-03-19 21:59 UTC, digant73 commented on TFT/src/User/Menu/ABL.c
>  {
restore the original file

2021-03-19 21:59 UTC, digant73 commented on TFT/src/User/Menu/ABL.h
>  }
restore the original file

2021-03-19 21:59 UTC, digant73 commented on platformio.ini
>    -DRAM_SIZE=64  ; Available RAM size in kbytes
restore the original file

2021-03-20 00:25 UTC, Cal1sto commented
Files restored from source repository, No change to be performed on Configuration.h, platformio.ini, ABL.c and ABL.h

2021-03-20 04:53 UTC, AntoszHUN commented
> @Acenotass @AntoszHUN @bepstein111
> 
> One Icon more, sorry.
> 
> But like BTT wrote, there is no need to hurry, as all new features will be released next week, once the new firmware is available.
> 
> Thank you all!

I do not see. What icon? What is the name?

2021-03-20 05:46 UTC, oldman4U commented
Look what Guilouz  wrote and attached yesterday.

2021-03-20 09:09 UTC, Cal1sto commented
Please could someone advise how to remove the ABL.c, ABL.h, Configuration.h and platformio.ini from this PR, there is no change on this files, i replace all this from origin master, but still on some strange difference :
- New line (char) at the end of the files
- ABL.c Diff not reflecting the reality ? Or wrong compare result ?

2021-03-20 11:02 UTC, digant73 commented
> Please could someone advise how to remove the ABL.c, ABL.h, Configuration.h and platformio.ini from this PR, there is no change on this files, i replace all this from origin master, but still on some strange difference :
> 
> * New line (char) at the end of the files
> * ABL.c Diff not reflecting the reality ? Or wrong compare result ?

possibly it's just wrong report from github. forget it at the moment. Eventually I will restore the proper files

2021-03-20 11:11 UTC, digant73 requested changes

2021-03-20 11:11 UTC, digant73 commented on TFT/src/User/API/coordinate.c
> +    levelCornerPosition[point] = position;
2 spaces for indentation, not 4

2021-03-20 11:11 UTC, digant73 commented on TFT/src/User/API/coordinate.c
> +    return levelCornerPosition[point];
2 spaces for indentation, not 4

2021-03-20 11:11 UTC, digant73 commented on TFT/src/User/Menu/ABL.c
>        storeCmd("G29\n");
merge ABL.c with the last BTT changes

2021-03-20 11:11 UTC, digant73 commented on TFT/src/User/Menu/BedLevelingLayer2.c
> +          infoMenu.menu[++infoMenu.cur] = menuLevelCorner;
reduce the indetation so it is at teh same level of "break"

2021-03-20 11:11 UTC, digant73 commented on TFT/src/User/Menu/LevelCorner.c
> +}
put a new line after "}"

2021-03-20 11:11 UTC, digant73 commented on TFT/src/User/Menu/LevelCorner.h
> +#endif
put a new line after #endif"

2021-03-20 18:23 UTC, digant73 commented
@Cal1sto if I'm not wrong your PR implements FR #1646, so please at the end of the PR description report the following line:

resolves #1646

2021-03-20 21:45 UTC, Cal1sto commented
@digant73 Thanks yes it seems a request related and matched with the FR #1646, PR description updated.

2021-03-21 00:05 UTC, Cal1sto commented
@digant73 Could you check if the ABL.c in this PR is now the origin/master (bigtreetech:master) one, i am not sure if i did it right because i don't see anw difference in the files changed section, and then if not i need your help to do it correctly, thanks

2021-03-21 02:22 UTC, Cal1sto commented
@bigtreetech You could merge this PR, the conflict resulted to other merge are now solved. thanks

2021-03-21 09:48 UTC, digant73 requested changes

2021-03-21 09:48 UTC, digant73 commented on TFT/src/User/API/coordinate.c
> +// Set level corner position the measured Z offset from probe, see in ABL.c menu refreshLevelCornerValue(MENUITEMS levelItems) and value get from parseACK.c
move your new two functions after coordinateQuery so you will respect the same order in the .h file

2021-03-21 09:48 UTC, digant73 commented on TFT/src/User/API/parseACK.c
> +      }
put a new line after }

2021-03-21 09:48 UTC, digant73 commented on TFT/src/User/Menu/ABL.c
> +
remove the two spaces, just leave the empty line

2021-03-21 09:48 UTC, digant73 commented on TFT/src/User/Menu/LevelCorner.c
> +  if ( (int)GetLevelCornerPosition(0) != 0)
remove the space after (

2021-03-21 09:48 UTC, digant73 commented on TFT/src/User/Menu/LevelCorner.c
> +    if (((int)GetLevelCornerPosition(0) >= 1) && ((int)GetLevelCornerPosition(0) <= 4) )
remove the space before the last )

2021-03-21 09:48 UTC, digant73 commented on TFT/src/User/Menu/LevelCorner.c
> +  /* Init Probe Offset in parseAck to get probe offset X and Y*/
convert all the /* comments to // (single line comments is preferred)

2021-03-21 09:48 UTC, digant73 commented on TFT/src/User/Menu/LevelCorner.c
> +    infoSettings.level_edge = ((LEVELING_EDGE_DISTANCE >= edge_min)?LEVELING_EDGE_DISTANCE:edge_min);
separate "?" and ":" with a space before and after

2021-03-21 09:48 UTC, digant73 commented on TFT/src/User/Menu/LevelCorner.c
> +      case KEY_ICON_1:
put a new line between each "case" statement

2021-03-21 09:48 UTC, digant73 commented on TFT/src/User/Menu/LevelCorner.c
> +          infoSettings.level_edge = ((val >= edge_min)?val:edge_min);
as for the previuous "?" and ":"

2021-03-21 09:48 UTC, digant73 commented on TFT/src/User/Menu/LevelCorner.c
> +const MENUITEMS levelcornerItems = {
wrong indentation. cut&paste the menu at the beginning of PID.c and change the values (labels must continue to start at column 36)

2021-03-21 14:07 UTC, digant73 requested changes

2021-03-21 14:07 UTC, digant73 commented on TFT/src/User/Menu/LevelCorner.c
> +
remove this blank line

2021-03-21 14:07 UTC, digant73 commented on TFT/src/User/Menu/LevelCorner.c
> +  {
remove all the tabs character

2021-03-21 21:00 UTC, Guilouz commented
Just try your PR and it's not working as expected for me...

When I clic on L Corner icon, probing run directly and points 2 and 4 are always in error, can do nothing on the screen and freeze after a while. This process never stops, probe of the 4 corners turns in a loop.

Here a video of this issue : https://www.youtube.com/watch?v=Miibz6StZao

With level bed corner from Marlin I don't have issue : https://www.youtube.com/watch?v=FMbsn1hwxnU

2021-03-21 23:10 UTC, Cal1sto commented
LevelCorner.c now with the fix of the in G30 fonction modified in last Marlin bug fix release 
https://github.com/MarlinFirmware/Marlin/pull/20437
TouchMi will use the G30 E0 and other Probe like BL-Touch the G30 E1

2021-03-23 00:13 UTC, Cal1sto commented
In preparation i will add M48 to have a visual view on the probe accuracy on this page level to help in precision decision.

2021-03-23 10:40 UTC, Cal1sto commented
M48 added in this menu Level corner

2021-03-23 12:13 UTC, Cal1sto commented
Due that the M48 made motor off i add the M17 call to made motor on on  X, Y and Z

2021-03-23 23:00 UTC, Guilouz commented
PR tested and working but a small graphical issue, text overflows from icon on TFT43

![162471021_2049340218546818_1918169376129697798_n](https://user-images.githubusercontent.com/12702322/112229800-ed74af00-8c33-11eb-9299-038c00411aa0.jpg)

2021-03-24 11:35 UTC, Cal1sto commented
@Guilouz Please check again on your TFT43,  should look better now , moved the text up and made only 1px shadow. Better than creating a new icon for this single function.

2021-03-24 11:49 UTC, Guilouz commented
> @Guilouz Please check again on your TFT43, should look better now , moved the text up and made only 1px shadow. Better than creating a new icon for this single function.

There is still 1 pixel too much to the left and there the text overlaps the BLTouch icon.

2021-03-24 21:40 UTC, Cal1sto commented
![20210324_223112](https://user-images.githubusercontent.com/47449942/112386783-acdb6b00-8cf1-11eb-877c-e328d5cffee1.jpg)
Last zn hope final generic proposition on a TFT28 should now also be good on other screen size or icon size

2021-03-24 21:55 UTC, oldman4U commented
Maybe you want to give it a try to put the 4 blue buttons in the upper row and everything else below. Doing so it would be easier to "find" the buttons without looking too much onto the screen.

Maybe you covered this topic before: Why are the number much closed to the buttons than the text elements?

Just my 2 cents

2021-03-24 22:34 UTC, Guilouz commented
Perfect on TFT43

![6E5649CD-0799-49DD-B2B4-4983C2F3386A](https://user-images.githubusercontent.com/12702322/112392257-62f68300-8cf9-11eb-95de-828f2b145865.jpeg)

2021-03-25 00:20 UTC, Cal1sto commented
![20210325_011708](https://user-images.githubusercontent.com/47449942/112400097-e919c600-8d07-11eb-8e01-cd64ddf184f9.jpg)
Adjusted with same procedure as the one used for displaying label, should now be same position as the one for Label

2021-03-25 08:31 UTC, Cal1sto commented
> Maybe you want to give it a try to put the 4 blue buttons in the upper row and everything else below. Doing so it would be easier to "find" the buttons without looking too much onto the screen.
> 
> Maybe you covered this topic before: Why are the number much closed to the buttons than the text elements?
> 
> Just my 2 cents

For the 4 corners blue (cyan) icons, this disposition on the screen is spacialy the same as the bed front of the user and therefore intuitive. For this reason i will suggest to let it like that.

2021-03-26 11:18 UTC, Cal1sto commented
Added M18 S0 X Y Z to reduce the risk when MARLIN is not set without stepper timeout, that user could not after an inactivity time move the axis, should also be integrated in Z-align procedure to reduce the move of the Z-axis after timeout is falling.

2021-03-26 13:52 UTC, Cal1sto commented
Added after G34  (Z-Alignment) the call of M18 S0 X Y Z , to reduce the risk when Marlin is not compiled with no timeout on the stepper that the Axes could move.

2021-03-26 13:59 UTC, Cal1sto commented
Added value refresh that was missing after setting new corner offset point.

2021-03-26 14:10 UTC, Cal1sto commented
So nothing else to add there, is everything so far tested and ready , enjoy

2021-03-26 14:16 UTC, Cal1sto commented
@bigtreetech So far ready

2021-03-30 08:49 UTC, Cal1sto commented
Last fine tuning to force coordinate init on going into "L Corner", to reduce risk because the coordinateIsKnown() function is not accurate when motor are off over Marlin or other function.

2021-03-30 10:14 UTC, digant73 commented
@Cal1sto if I can suggest a layout, I would move:
* the "start" button on the left of "back" button
* the "M48" button above "back" button
* the "distance" button" on the left of the new "M48" position (so on top at 3rd position from left)
That layout will be more similar to other menus (e.g. manual leveling, MBL etc...)

2021-03-30 11:11 UTC, Cal1sto commented
@digant73 Yes good idea it is done

2021-03-30 13:24 UTC, Cal1sto commented
We are testing, the last change , is not validated yet

2021-03-30 13:34 UTC, Cal1sto commented
Last menu function reordering is tested and worked, like expected

2021-04-01 09:19 UTC, ETE-Design commented
@Cal1sto There seems to be 2 different ways to do the messuring, one mesure each point one time and give the result at the end... The other messure 1 point and set it to be the "Zero" Point, move to the next, mesure it and show the result, then you adjust it, then it messure again you can keep on messure and adjust each point before go to the next, that way you can adjust on the go to get best result... Also if using solution two would it be possible to show "live" messurement if using an inductive / capasitive sensor instead of an BLTouch...

2021-04-01 11:32 UTC, Cal1sto commented
@ETE-Design The idea of the current implementation is to get from the mesured Z = 0 initialized with the Home (G28), the corner level , and adjust each on arround 0.01 precision, what is mostly enought . To be generic this implementation should work with all the probe able to give good accurency (see M48 function icon). So the solution provided here take the zero Z point on middle and display the difference on each corner. About inductive/capasitive sensor this should work if the accurency (precision) of the probe is enought, for this you could check it by pressing the M48 icons, what do you mean with live messurement, the live messurement is done when you press the start button.

2021-04-01 19:36 UTC, ETE-Design commented
@Cal1sto So to understand it right it stop at each corner and let you level it before it goes to the next corner? About "Live" Messurement I was thinking about letting the sensor stand over one corner when you level it, then let the Inductive / Capasitive sensor messure all the time since it dosen't need to raise / lower the probe to messure as long as the bed is close enough it will be possible to see the exact messurement all the time... This is of cause not possible with a BLTouch since the probe need to touch the bed each time to get the messurement.

2021-04-01 20:52 UTC, Cal1sto commented
@ETE-Design I make it generic and simple enought to all user, i do not integrate a logic analysis depending on the accurency of the probe to make this automatismus, an automatismus will be great with a motor on each screw that is yet not used on mostly printer. Therefore this version will be integrated like it is , and when you use it like i did you will be happy to have the possibility to make your bed in a better leveling state than the paper mode leveling. Try and enjoy.

2021-04-07 01:30 UTC, merged

2021-04-27 20:45 UTC, discip commented
@Cal1sto
Good evening sir,
I am somewhat confused, because I can't get this to work.
I am on the latest commit https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/commit/0f464dc0e95d12f60a49a8a66fba9045e84b6274 and no matter what I do, it does not work for me.
What exactly do I have define in *Marlin* or set in *config.ini*, to make this feature work?
thank you in advance
kind regards