Neopixel LED number config
bigtreetech/BIGTREETECH-TouchScreenFirmware pull request #1844
Opened 2021-04-16 10:36 UTC by Msq001

### Description
Now we can set the  number of LED(neopixel)  in the `config.ini` file

### Benefits

### Related Issues
fix #1764

2021-04-16 20:49 UTC, oldman4U commented
Hi. How to connect this to the TFT35 E3 v3.0?

Btw, I believe there is a typo related to this TFT in the config.ini

2021-04-16 22:25 UTC, Guilouz requested changes

2021-04-16 22:25 UTC, Guilouz commented on Copy to SD Card root directory to update/config.ini
> +# Set the number of LEDs in the strip connected the "Neopixle" port of TFT.
"Neopixle" must be "Neopixel"

2021-04-16 22:25 UTC, Guilouz commented on Copy to SD Card root directory to update/config_rrf.ini
> +# Set the number of LEDs in the strip connected the "Neopixle" port of TFT.
"Neopixle" must be "Neopixel"

2021-04-16 22:25 UTC, Guilouz commented on TFT/src/User/config.ini
> +# Set the number of LEDs in the strip connected the "Neopixle" port of TFT.
"Neopixle" must be "Neopixel"

2021-04-19 05:22 UTC, merged

2021-04-20 07:00 UTC, oldman4U commented
Ok. So it is time to activate my TFT43 finally👍🏻😁