Klipper 12864 improve
bigtreetech/BIGTREETECH-TouchScreenFirmware pull request #1913
Opened 2021-05-13 06:30 UTC by Msq001

### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

### Benefits

### Related Issues

2021-05-13 09:43 UTC, oldman4U commented
Hi.

Should we ask the Klipper users to test this PR?

2021-05-13 10:14 UTC, Msq001 commented
This feature can be used normally, but the code needs more cleaning. After cleaning, I will convert to `Ready for review`, and then ask members to test

2021-05-13 10:28 UTC, oldman4U commented
Perfect. 

Thank you

2021-05-14 04:32 UTC, guruathwal commented on TFT/src/User/API/boot.c
> +          updateFont(FONT_ROOT_DIR "/16x8_byte_ascii.fon", _16X8_FONT_ADDR) &&
@Msq001 Please rename 16x8 to 8x16

2021-05-15 09:36 UTC, digant73 commented on TFT/src/User/API/UI/ST7920_Emulator.c
too much indentation

2021-05-18 13:15 UTC, digant73 requested changes

2021-05-18 13:15 UTC, digant73 commented on TFT/src/User/API/UI/ST7920_Emulator.h
> +}ST7920;
a space after }

2021-05-21 08:47 UTC, oldman4U commented
So the reaction of the community is overwhelming....

Have you got something back?

2021-05-22 09:40 UTC, merged

2021-06-03 12:49 UTC, Talha909 commented
My lcd show the result on screen. But rotary switch did not work.  What should i do

2021-06-03 16:46 UTC, jasc76 commented
Tested this on TFT24 with MKS GEN L with the provided [display] section above. 

Klippy Error:
Unknown value 'EXP2_1' in enumeration 'pin'
This type of error is frequently caused by running an older
version of the firmware on the micro-controller (fix by
recompiling and flashing the firmware).

Known versions: host=v0.9.1-533-g27f8cf02, mcu=v0.9.1-528-gc0d86048

printer.cfg
aliases:
    # EXP1 header
    EXP1_1=ar37, EXP1_3=ar17, EXP1_5=ar23, EXP1_7=ar27, EXP1_9=<GND>,
    EXP1_2=ar35, EXP1_4=ar16, EXP1_6=ar25,  EXP1_8=ar29, EXP1_10=<5V>

    # EXP2 header
    EXP2_1=ar50, EXP2_3=ar31, EXP2_5=ar33, EXP2_7=ar49, EXP2_9=<GND>,
    EXP2_2=ar52, EXP2_4=ar53, EXP2_6=ar51,  EXP2_8=<RST>, EXP2_10=ar41

[display]
lcd_type: emulated_st7920
spi_software_miso_pin: EXP2_1
spi_software_mosi_pin: EXP1_3
spi_software_sclk_pin: EXP1_5
en_pin: EXP1_4
encoder_pins: ^EXP2_5, ^EXP2_3
click_pin: ^!EXP1_2
[output_pin beeper]
pin: EXP1_1

2021-06-05 01:19 UTC, bigtreetech commented
> My lcd show the result on screen. But rotary switch did not work. What should i do

Which motherboard do you use? Maybe there is something wrong with the setting of 
```
encoder_pins: ^EXP2_3, ^EXP2_5
click_pin: ^!EXP1_2
```

2021-06-05 01:34 UTC, bigtreetech commented
> Klippy Error:
> Unknown value 'EXP2_1' in enumeration 'pin'
> This type of error is frequently caused by running an older
> version of the firmware on the micro-controller (fix by
> recompiling and flashing the firmware).
> 
> Known versions: host=v0.9.1-533-g27f8cf02, mcu=v0.9.1-528-gc0d86048

Do you using the latest version of klipper and the MCU of MKS GEN L has also updated the latest version of firmware.bin?

2021-06-05 03:49 UTC, jasc76 commented
Known versions: host=v0.9.1-533-g27f8cf02, mcu=v0.9.1-533-g27f8cf02, rpi=v0.9.1-533-g27f8cf02

no change, error still is there. Its the latest kiauh is offering

What I discovered:
Changing
spi_software_miso_pin: EXP2_1
to
spi_software_miso_pin: EXP2_**2** (was just an idea, what happens) 
the error goes away and it wors

2021-06-08 06:19 UTC, Talha909 commented
I am using skr 1.4 Tubo. I got the display on the screen but my rotary switch did not work and there is no beeper. What should i do

2021-06-08 07:12 UTC, oldman4U commented
Contact your dealer.

2021-06-08 08:43 UTC, bigtreetech commented
> I am using skr 1.4 Tubo. I got the display on the screen but my rotary switch did not work and there is no beeper. What should i do

Hello, Can you confirm that the following pins are set properly? If you are still unable to work after confirmation, please provide your `printer.cfg` file
```
encoder_pins: ^EXP2_3, ^EXP2_5
click_pin: ^!EXP1_2

[output_pin beeper]
pin: EXP1_1
```

2021-06-09 04:53 UTC, Talha909 commented
HI, Still facing the issue. My rotary switch is not working. I am using SKR 1.4 Tubo, TMC2130 and TFT 24
[printer (5).zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6621190/printer.5.zip)

2021-06-20 07:59 UTC, gregmatic commented
my screen shows Marlin Mode with blank screen. can anyone confirm the following works with SKR E3 Mini v1.2 & TFT35 E3 V3.0?

[board_pins]
aliases:
    # EXP1 header
    EXP1_1=PB5, EXP1_3=PA9,   EXP1_5=PA10, EXP1_7=PB8, EXP1_9=<GND>,
    EXP1_2=PB6, EXP1_4=<RST>, EXP1_6=PB9,  EXP1_8=PB7, EXP1_10=<5V>

[display]
lcd_type: emulated_st7920
spi_software_miso_pin: EXP2_1
spi_software_mosi_pin: EXP1_3
spi_software_sclk_pin: EXP1_5
en_pin: EXP1_4
encoder_pins: ^EXP2_3, ^EXP2_5
click_pin: ^!EXP1_2

2021-06-22 10:38 UTC, bigtreetech commented
> my screen shows Marlin Mode with blank screen. can anyone confirm the following works with SKR E3 Mini v1.2 & TFT35 E3 V3.0?
> 
> [board_pins]
> aliases:
> # EXP1 header
> EXP1_1=PB5, EXP1_3=PA9, EXP1_5=PA10, EXP1_7=PB8, EXP1_9=,
> EXP1_2=PB6, EXP1_4=, EXP1_6=PB9, EXP1_8=PB7, EXP1_10=<5V>
> 
> [display]
> lcd_type: emulated_st7920
> spi_software_miso_pin: EXP2_1
> spi_software_mosi_pin: EXP1_3
> spi_software_sclk_pin: EXP1_5
> en_pin: EXP1_4
> encoder_pins: ^EXP2_3, ^EXP2_5
> click_pin: ^!EXP1_2

According to the instructions here
https://github.com/KevinOConnor/klipper/blob/478f26cab6c8e73e3970d2b303bc818f6910ae74/config/sample-lcd.cfg#L49
SKR-mini-E3-V1.2 has no EXP1 + EXP2 and only the Ender-3 stock display port, so the settings should be as follows


```
[display]
lcd_type: st7920
cs_pin: EXP1_7
sclk_pin: EXP1_6
sid_pin: EXP1_8
encoder_pins: ^EXP1_5, ^EXP1_3
click_pin: ^!EXP1_2

[output_pin beeper]
pin: EXP1_1
```

2021-06-23 14:10 UTC, gregmatic commented
> [display]
lcd_type: st7920
cs_pin: EXP1_7
sclk_pin: EXP1_6
sid_pin: EXP1_8
encoder_pins: ^EXP1_5, ^EXP1_3
click_pin: ^!EXP1_2

[output_pin beeper]
pin: EXP1_1


thank you...i tried this but Marlin Mode still shows black screen. I didn't move any wiring ...the TFT35 worked fine in both Marlin Mode & Touch Mode when my firmware was Marlin...

2021-07-29 07:49 UTC, Terixxx commented
How it is possible to connect TFT3.5 V3.0 to BTT Octopus V1.1 
[display]
lcd_type: emulated_st7920
spi_software_miso_pin: EXP2_1
spi_software_mosi_pin: EXP1_3
spi_software_sclk_pin: EXP1_5
en_pin: EXP1_4
encoder_pins: ^EXP2_3, ^EXP2_5
click_pin: ^!EXP1_2
Тhese pins are totally not as in board pin mapping. And how to be sure which pinout is correct. The official config file in repository for Octopus board is: 

[board_pins]
aliases:
    # EXP1 header
    EXP1_1=PE8, EXP1_2=PE7,
    EXP1_3=PE9, EXP1_4=PE10,
    EXP1_5=PE12, EXP1_6=PE13,    # Slot in the socket on this side
    EXP1_7=PE14, EXP1_8=PE15,
    EXP1_9=<GND>, EXP1_10=<5V>,

    # EXP2 header
    EXP2_1=PA6, EXP2_2=PA5,
    EXP2_3=PB1, EXP2_4=PA4,
    EXP2_5=PB2, EXP2_6=PA7,      # Slot in the socket on this side
    EXP2_7=PC15, EXP2_8=<RST>,
    EXP2_9=<GND>, EXP2_10=<5V>

But how this is possible when:
**spi_software_miso_pin: EXP2_1
spi_software_mosi_pin: EXP1_3
spi_software_sclk_pin: EXP1_5**

but regarding on https://raw.githubusercontent.com/bigtreetech/BIGTREETECH-OCTOPUS-V1.0/master/Hardware/BIGTREETECH%20Octopus.pdf
SPI1_MISO -> PA6
SPI1_MOSI -> PA7
SPI1_SCK    -> PA5
FORGET IT!!!!!!!! I am totally lost in this wrong diagrams and pinouts!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
https://github.com/bigtreetech/BIGTREETECH-OCTOPUS-V1.0/blob/master/Octopus%20works%20on%20Voron%20v2.4/Firmware/Klipper/BTT_OctoPus_Voron2_Config.cfg
I can't believe that this is happens with BTT OOCTOPUS BOARD!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! This is not possible.

2021-07-29 11:02 UTC, Terixxx commented
> 
> ### Requirements
> 
> [KevinOConnor/klipper#3979](https://github.com/KevinOConnor/klipper/pull/3979) This PR of Klipper has solved the SPI data shift problem of TFT 12864 mode(Thanks @teeminus)
> According to the setting in [KevinOConnor/klipper#3979 (comment)](https://github.com/KevinOConnor/klipper/pull/3979#issuecomment-784215162), the TFT 12864 can work normally with Klipper
> 
> We need to set `lcd_type` to `emulated_st7920`, and set the correct pin of `software_spi`
> 
> ```
> [display]
> lcd_type: emulated_st7920
> spi_software_miso_pin: EXP2_1
> spi_software_mosi_pin: EXP1_3
> spi_software_sclk_pin: EXP1_5
> en_pin: EXP1_4
> encoder_pins: ^EXP2_3, ^EXP2_5
> click_pin: ^!EXP1_2
> ```
> 
> ### Description
> TFT work with SKR-2 	Marlin & Full Screen OFF 	Marlin & Full Screen ON 	Klipper & Full Screen OFF 	Klipper & Full Screen ON
> TFT24 V1.1 	💚good 	⚠️beta 	💚good 	⚠️beta
> TFT35 E3 V3.0 	💚good 	💚good 	💚good 	💚good
> TFT50 V3.0 	💚good 	💚good 	💚good 	💚good
> TFT70 V3.0 	💚good 	💚good 	💚good 	💚good
> 
> It reduces ram loss of hundreds of bytes and increases flash of tens of bytes
> ### Benefits
> ### Related Issues
> 
> fixed #290

Could you please provide Pin map and board corresponding to this configuration

2021-08-12 13:46 UTC, hapklaar commented
@Msq001 This is working for me, except for that the screen gets garbled/scrambled after a few minutes of printing. Tried both ways of addressing the screen, doesn't seem to matter for this specific problem.

```
[display]
lcd_type: st7920 
cs_pin: EXP1_4
sclk_pin: EXP1_5
sid_pin: EXP1_3
encoder_pins: ^EXP2_5, ^EXP2_3
click_pin: ^!EXP1_2
```

and
```
[display]
lcd_type: emulated_st7920
spi_software_miso_pin: EXP2_1
spi_software_mosi_pin: EXP1_3
spi_software_sclk_pin: EXP1_5
en_pin: EXP1_4
encoder_pins: ^EXP2_3, ^EXP2_5
click_pin: ^!EXP1_2
```

2022-01-24 00:37 UTC, vMeph commented
@Msq001 could you provide the config for the btt SKR2 to testout
thanks in advanced

2022-01-25 19:43 UTC, vMeph commented
its working !!!

2022-02-10 08:02 UTC, mlaci001 commented
The same is true with the E3 turbo and TFT35-E3-v3.
The screen is blank.
If the TFT button is held down for 3 seconds, the mode selection window will appear, here you have to select the Marlin mode (no matter what mode the screen is in).
The screen will still be blank, but if you press the button again, the menu will appear and work from there.
You have to do it again every time you start.
I don't know why it's not good at startup.
I can't use emulated_st7920 mode, the motherboard only has an EXP1 connector.

2022-03-30 16:21 UTC, chaicracker commented
Hello everyone :)

Currently trying to get a BTT TFT35 V3 (the wide one, not the E3 version) working with an SKR Mini E3 V2.0

this is the configuration I could muster so far, though none of the tries suceeded so far. I had installed the fitting NoTouchScreenFirmware for the Display and says "ST7920Emulated ready"

`[board_pins]
aliases:
    EXP1_1=PB5,  EXP1_3=PA9,   EXP1_5=PA10, EXP1_7=PB8,  EXP1_9=<GND>,
    EXP1_2=PA15, EXP1_4=<RST>, EXP1_6=PB9,  EXP1_8=PB15, EXP1_10=<5V>,


[display]
lcd_type: emulated_st7920
en_pin: EXP1_7
spi_software_sclk_pin: EXP1_6
spi_software_mosi_pin: EXP1_8
spi_software_miso_pin: PA3
encoder_pins: ^EXP1_5, ^EXP1_3
click_pin: ^!EXP1_2`

Cheers :)

2022-10-07 08:03 UTC, douglasdtlltd commented
> 

This works with the current compile of the BTT firmware and a BTT SKR Mini E3 V2 with THESE PINS.

IM SO HAPPY I FOUND THIS.