Add gantry position auto report support
bigtreetech/BIGTREETECH-TouchScreenFirmware pull request #1924
Opened 2021-05-17 14:18 UTC by guruathwal

- Add gantry position auto report support (through M154 if available in Marlin firmware).
- Auto-detect Position auto report from M115 response from Marlin firmware.
- Clean up some code.

Resolves: #1921

2021-05-17 17:22 UTC, radek8 commented
Thank you very much.
Can you also add a comment to the config.ini file?
 
General options:
AUTO_REPORT_POSITION (in Configuration_adv.h)

2021-05-17 18:31 UTC, oldman4U commented
I will add it also to the ReadMe once merged.

2021-05-18 12:38 UTC, digant73 requested changes

2021-05-18 12:38 UTC, digant73 commented on Copy to SD Card root directory to update/config.ini
> +#   AUTO_REPORT_POSITION (in Configuration_adv.h)
the parameters were listed in the same order they appear in Configuration.h / Configuration_adv.h. So AUTO_REPORT_POSITION should be provided just before M115_GEOMETRY_REPORT

2021-05-19 05:29 UTC, merged